const EventType = Object.freeze({
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  USER_PROMPT: 'USER_PROMPT',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_COMPLETED: 'AGENT_COMPLETED',
  AGENT_FAILED: 'AGENT_FAILED',
  LLM_CALL: 'LLM_CALL',
  AGENT_CALL: 'AGENT_CALL',
  TOOL_CALL: 'TOOL_CALL',
  FILE_CHANGE: 'FILE_CHANGE',
  SKILL_CALL: 'SKILL_CALL',
  TEST_RUN: 'TEST_RUN',
  ERROR: 'ERROR',
});

module.exports = { EventType };
